### ISSUE TITLE
Asking Sample code 

### ISSUE THREAD

**Issue by liverlive** [ollyxar/websockets-chat#1]
Can you send me a sample code where you are sending message just to one person not to all of them?

**Comment by alexslipknot** [comment]
Hello. I'm afraid I cannot write simple small example. Just because it depends on User model in your project and I don't know how you will process direct message. 
But I can describe you how to deliver message to the needed client.
You have to implement search function in the `onFilteredMessage` method. Here you can define target user with assigned socket client and use `fwrite` to send message to him

**Comment by alexslipknot** [comment]
Also there is another non-secure approach: You can specify userId in the message and show it only if logged user has the same id

**Comment by alexslipknot** [comment]
I hope my answer helps you.
I decide to create another project to show you how to build Laravel Messenger. Because this topic about Laravel Chat and your question more relevant to Messenger
